// Obtener todas las recetas

// Obtener una receta específica

// Agregar una nueva receta
Content-Type: application/json

{
    "nombre":"huevo",
    "cantidad":"1",
    "unidadMedida":"0"
}

// Modificar una receta existente
Content-Type: application/json

{
    "nombre":"huevo",
    "cantidad":"1",
    "unidadMedida":"0"
}

// Eliminar una receta
