// Obtener todas las recetas

// Obtener una receta específica

// Agregar una nueva receta
Content-Type: application/json

{
    "titulo":"Huevo Duro"
    "ingredientes":"Huevo"
    "instrucciones":"Tan"
    "tiempoPreparacion":"5 minutos"
    "dificultad":"Facil"
    "categoria":""
}
// Modificar una receta existente
Content-Type: application/json

{
    "titulo":"Huevo Duro"
    "ingredientes":"Huevo"
    "instrucciones":"Tan"
    "tiempoPreparacion":"5 minutos"
    "dificultad":"Facil"
    "categoria":""
}

// Eliminar una receta
