### Obtener todos los usuarios

### Obtener un usuario


### Enviar un nuevo usuario
Content-Type: application/json

{
    "nombre": "Admin",
    "apellido": "Admin",
    "email": "admin@admin.com", 
    "password": "Password1",
    "genero": "femenino",
}

### Modificar un usuario
Content-Type: application/json

{
    "nombre": "Admin",
    "apellido": "Admin",
    "email": "admin@admin.com", 
    "password": "Password1",
    "genero": "femenino",
}

### Eliminar un usuario
